inventory/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('add/', views.item_create),
    path('<int:pk>/delete_item/', views.delete_item, name="delete_item"),
    path('<int:pk>/modify_item/', views.modify_item, name="modify_item")
]

testCbPlus/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('inventory/', include('inventory.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

inventory/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator


# Create your models here.

class Inventory(models.Model):
    name = models.CharField(default="test", max_length=200, blank=True)
    gtin = models.CharField(default='0000000000000', max_length=13, validators=[RegexValidator(r'^\d{13,13}$')])
    expiry_date = models.DateField('expiry date')
    image_url = models.URLField(default='', editable=False)
    def __str__(self):
        return self.name

    def is_outdated(self):
        return self.expiry_date <= timezone.now().date()

    def get_expiry_date(self):
        return self.expiry_date
        
    def get_gtin(self):
        return self.gtin

    def get_image_url(self):
        return self.image_url

inventory/forms.py
from django import forms
from .models import Inventory

class ItemForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = [
            'name',
            'gtin',
            'expiry_date'
        ]

inventory/views.py
from django.shortcuts import get_object_or_404, render
from django.template import loader

from .forms import ItemForm

from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect

from .models import Inventory

from requests import get, exceptions

# Create your views here.

def index(request):
    latest_inventory_list = Inventory.objects.order_by('expiry_date')
    template = loader.get_template('inventory/index.html')
    context = {
        'latest_inventory_list': latest_inventory_list,
    }
    return HttpResponse(template.render(context, request))

def item_create(request):
    form = ItemForm(request.POST)
    if form.is_valid():
        item = form.save(commit=False)
        try:
            response = get('https://world.openfoodfacts.org/api/v0/product/{}.json'.format(item.gtin), timeout=5)
            openFoodFactData = response.json()
            item.name = openFoodFactData['product']['product_name']
            item.image_url = openFoodFactData['product']['image_front_small_url']
        except ConnectionError as e:
            print(e)
        except Exception as e:
            print(e)

        for i in Inventory.objects.all():
            if i.gtin == item.gtin:
                i.expiry_date = item.expiry_date
                i.save()
                return HttpResponseRedirect(reverse('index'))
        item.save()
        return HttpResponseRedirect(reverse('index'))
    return render(request, "inventory/add.html", {'form': form})

def delete_item(request, pk): 
    Inventory.objects.get(id=pk).delete()
    return HttpResponseRedirect(reverse('index'))

def modify_item(request, pk):
    item = Inventory.objects.get(id=pk)
    form = ItemForm(request.POST)
    if form.is_valid():
        itemF = form.save(commit=False)
        item.name = itemF.name
        item.expiry_date = itemF.expiry_date
        for i in Inventory.objects.all():
            if i.gtin == itemF.gtin:
                item.save()
                return HttpResponseRedirect(reverse('index'))
        item.gtin = itemF.gtin
        item.save()
        return HttpResponseRedirect(reverse('index'))
    context = {
        'form': form,
        'item': item
    }
    return render(request, "inventory/modify.html", context)


def detail(request, id):
    item = get_object_or_404(Inventory, pk=id)
    return render(request, 'inventory/detail.html', {'item': item})

inventory/templates/inventory/add.html
<html>
    <head>
        <title>Inventory : Add item</title>
        <style>
        body {
                background-color: white;
            }
            hr {
                color: green;
            }
            h1, p {
                color : green;
            }
            a {
                text-decoration: none;
                color: green;
            }
            a:hover {
                color:greenyellow;
            }
            .left_band {
                background-image: url("/static/left.jpg");
                background-repeat: no-repeat;
                background-size: cover;
                width: 20%;
                height: 100%;
                position: fixed;
                top: 0; left: 0;
                margin: 0; padding: 0;
            }
            .right_band {
                background: url("/static/right.jpg");
                background-repeat: no-repeat;
                background-size: cover;
                width: 20%;
                position: fixed;
                height: 100%;
                top: 0; right: 0;
                margin: 0; padding: 0;
            }
            .content {
                text-align: center;
                margin-left: 20%;
                width: 60%;
            }
        </style>
    </head>
    <body>
        <div class="left_band">
        </div>
        <div class="right_band">
        </div>
        <div class="content">
        <h1>Add item to inventory</h1>
        <p>Be careful, adding a new item with an existing GTIN will only modify the existing item GTIN</p>
        <Hr>
        <form method='POST'> {% csrf_token %}

            <ul class="errorlist"><li>This field is required.</li></ul>
            <p><label for="id_gtin">Gtin:</label> <input type="text" name="gtin" maxlength="13" required id="id_gtin"></p>
            <ul class="errorlist"><li>This field is required.</li></ul>
            <p><label for="id_expiry_date">Expiry date:</label> <input type="text" name="expiry_date" required id="id_expiry_date"></p>

            <a href="../"><input type="submit" value="Save" /></a>
        </form>
        <HR>
        <button><a href="../">Back</a></button>
        </div>
    </body>
</html>

inventory/templates/inventory/detail.html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Inventory : {{ item }}</title>
<style>
    body {
        background-color: white;
    }
    hr {
        color: green;
    }
    h1, p {
        color : green;
    }
    a {
        text-decoration: none;
        color: green;
    }
    a:hover {
        color:greenyellow;
    }
    .left_band {
        background-image: url("/static/left.jpg");
        background-repeat: no-repeat;
        background-size: cover;
        width: 20%;
        height: 100%;
        position: fixed;
        top: 0; left: 0;
        margin: 0; padding: 0;
    }
    .right_band {
        background: url("/static/right.jpg");
        background-repeat: no-repeat;
        background-size: cover;
        width: 20%;
        position: fixed;
        height: 100%;
        top: 0; right: 0;
        margin: 0; padding: 0;
    }
    .content {
        text-align: center;
        margin-left: 20%;
        width: 60%;
    }
</style>
</head>
<body>
    <div class="left_band">
    </div>
    <div class="right_band">
    </div>
    <div class="content">
    <h1>{{ item }}</h1>
    <p>This is an item labda page.</p>
    <hr>
    <BR>
    <p>
    GTIN : {{ item.gtin }}
    <br>
    Expiry date : {{ item.expiry_date }}
    </p>
    <BR>
    <hr>
    <button><a href="modify_item/">Modify</a></button>
    <button><a href="delete_item/">Remove</a></button>
    <button><a href="../">Back</a></button>
    </div>
</body>

inventory/templates/inventory/index.html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Inventory</title>
<style>
    body {
        background-color: white;
    }
    hr {
        color: green;
    }
    h1, p {
        color : green;
    }
    a {
        text-decoration: none;
        color: green;
    }
    a:hover {
        color:greenyellow;
    }
    .left_band {
        background-image: url("/static/left.jpg");
        background-repeat: no-repeat;
        background-size: cover;
        width: 20%;
        height: 100%;
        position: fixed;
        top: 0; left: 0;
        margin: 0; padding: 0;
    }
    .right_band {
        background: url("/static/right.jpg");
        background-repeat: no-repeat;
        background-size: cover;
        width: 20%;
        position: fixed;
        height: 100%;
        top: 0; right: 0;
        margin: 0; padding: 0;
    }
    .content {
        text-align: center;
        margin-left: 20%;
        width: 60%;
    }
    .image_product {
        vertical-align: middle;
        max-height: 200px;
        max-width: 200px;
    }
</style>
</head>
<body>
    <div class="left_band">
    </div>
    <div class="right_band">
    </div>
    <div class="content">
    <h1><U>INVENTORY</U></h1>
    <p>An item can be removed by accessing to his own page where you will find a remove button.</p>
    <hr>
    <BR>
    {% if latest_inventory_list %}
        {% for item in latest_inventory_list %}
            {% if item.is_outdated %}
            <a href="{% url 'detail' item.id %}">{{ item.name }} is outdated. <U><b>{{ item.expiry_date }}</b></U></a>
            {% else %}
            <a href="{% url 'detail' item.id %}">{{ item.name }} will be outdated after : <U><b>{{ item.expiry_date }}</b></U></a>
            {% endif %}
            <img class="image_product" src="{{item.image_url}}"/>
            <br><br>
        {% endfor %}
    {% else %}
        <p>No inventory are available.</p>
    {% endif %}
    <BR>
    <hr>
    <button><a href="add">Add Item</a></button>
    </div>
</body>
</html>

inventory/templates/inventory/modify.html
<html>
    <head>
        <title>Inventory : Modify item</title>
        <style>
        body {
                background-color: white;
            }
            hr {
                color: green;
            }
            h1, p {
                color : green;
            }
            a {
                text-decoration: none;
                color: green;
            }
            a:hover {
                color:greenyellow;
            }
            .left_band {
                background-image: url("/static/left.jpg");
                background-repeat: no-repeat;
                background-size: cover;
                width: 20%;
                height: 100%;
                position: fixed;
                top: 0; left: 0;
                margin: 0; padding: 0;
            }
            .right_band {
                background: url("/static/right.jpg");
                background-repeat: no-repeat;
                background-size: cover;
                width: 20%;
                position: fixed;
                height: 100%;
                top: 0; right: 0;
                margin: 0; padding: 0;
            }
            .content {
                text-align: center;
                margin-left: 20%;
                width: 60%;
            }
        </style>
    </head>
    <body>
        <div class="left_band">
        </div>
        <div class="right_band">
        </div>
        <div class="content">
        <h1>Modify item</h1>
        <p>Enter the same value if you want no changes, note that two items cannot have the same GTIN,
        <BR>so if you use an already assign GTIN, it wont be changed.
        <BR>
        <BR>Name : {{ item.name }} | GTIN : {{ item.gtin }} | Expiry date : {{ item.expiry_date }}
        </p>
        <Hr>
        <form method='POST'> {% csrf_token %}
            {{ form.as_p }}
            <a href="../"><input type="submit" value="Save" /></a>
        </form>
        <HR>
        <button><a href="../">Back</a></button>
        </div>
    </body>
</html>